version: '3'
services:
  postgres:
    image: "postgres:12.6-alpine"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
  


